### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by MarstonGouldExplore** [andydavies/WPT-Bulk-Tester#10]
I get the following error when I try to run my test:

Request failed for http://www.exploreconsulting.com/runtest.php?url=http%3A%2F%2Fwww.exploreconsulting.com%2Fresources%2Fnetsuite-customization-tips-and-tricks%2F&k=xxx&f=json&location=Dublin%3AChrome&runs=1&video=0&fvonly=1 returned code 404. Truncated server response: <!DOCTYPE html>   <html lang="en-US" prefix="og: http://og... (use muteHttpExceptions option to examine full response)

Settings

Name    Location    Runs    Video   First View Only
Dublin, Chrome, Cable   Dublin:Chrome   1   1   1

Example URL:

URL Scenario    WPT ID  Status  TTFB (ms)   Render Start (ms)   Visually Complete (ms)  DCL End (ms)    Load TIme (ms)  Speed Index Requests
http://www.exploreconsulting.com/resources/netsuite-customization-tips-and-tricks/  Dublin, Chrome, Cable

**Comment by andydavies** [comment]
It looks like you've put www.exploreconsulting.com as the WPT server address in the settings tab (B10) rather than ```http://webpagetest.org```

Can you confirm what's in cell B10 on the settings tab?

**Comment by MarstonGouldExplore** [comment]
Okay, dumb mistake. Thanks I fixed that.

Now however all I get back are 400 status with no results. Doesn't matter what URL I put in. I've tried about 30 different websites, they all come back 400s

**Comment by andydavies** [comment]
Someone else found this issue the other day - the WPT agent location names changed a while back - so Dublin wasn't a valid location.

If you use v0.4 of the sheet (linked in the readme) it should be OK now.
