### ISSUE TITLE
How to Map of columns in Test tab to WPT result fields		

### ISSUE THREAD

**Issue by AnkitSinghUtsav** [andydavies/WPT-Bulk-Tester#13]
Hello Andy,

I want to add some more fields in test result like 
CDN Score	data.median.firstView.score_cdn
Weight	data.median.firstView.fullyLoaded

Im added above parameter in Settings sheet. But its not reflected in test result. Please help me

Thanks

**Comment by spencershaw** [comment]
I have the same problem. Did you solve this?

**Comment by spencershaw** [comment]
You need to update the Named Range ResultsMap. To do this go to Setting tab and right click on the Map of columns in Test tab to WPT result fields and go to Define Range. You can then edit the ResultsMap Named Range. See screenshots:
	
![screenshot 2016-07-04 00 29 43](https://cloud.githubusercontent.com/assets/13031880/16548186/71dbab0a-417e-11e6-8ab3-8db0569a6fc2.png)
![screenshot 2016-07-04 00 24 50](https://cloud.githubusercontent.com/assets/13031880/16548174/442fe482-417e-11e6-85b2-933f7a442f82.png)

**Comment by andydavies** [comment]
@spencershaw Yup that's the way to do it
