### ISSUE TITLE
throttling

### ISSUE THREAD

**Issue by spencershaw** [andydavies/WPT-Bulk-Tester#15]
How do i specify throttling settings?

**Comment by spencershaw** [comment]
Posted too soon. Found this:
https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-restful-apis

> 
> Specifying connectivity
> 
> If the connectivity is not specified, by default you will get the Cable (5/1 Mbps, 28ms RTT) profile. The connectivity is specified as part of the location in the format:
> location:browser.connectivity
> 
> For example:
> Dulles_IE7.DSL
> Frankfurt.Dial
> China.custom
> Dulles:Chrome.DSL
> 
> The supported profiles for the public instance are:
> DSL - 1.5 Mbps down, 384 Kbps up, 50 ms first-hop RTT, 0% packet loss
> Cable - 5 Mbps down, 1 Mbps up, 28ms first-hop RTT, 0% packet loss
> FIOS - 20 Mbps down, 5 Mbps up, 4 ms first-hop RTT, 0% packet loss (not all locations will get the full bandwidth)
> Dial - 49 Kbps down, 30 Kbps up, 120 ms first-hop RTT, 0% packet loss
> 3G - 1.6 Mbps down, 768 Kbps up, 300 ms first-hop RTT, 0% packet loss
> 3GFast - 1.6 Mbps down, 768 Kbps up, 150 ms first-hop RTT, 0% packet loss
> Native - No synthetic traffic shaping applied
> custom - Custom profile, bandwidth and latency must also be specified using the bwIn, bwOut, latency and plr parameters

**Comment by spencershaw** [comment]
When I put for example ec2-eu-west-1:Chrome.3G in the Location field, it still gives the default Cable speed. What am I doing wrong

**Comment by andydavies** [comment]
I've just tried the following in the location field and they both work OK

ec2-eu-west-1:Chrome.3G - http://www.webpagetest.org/result/160704_RZ_Y1E/
ec2-eu-west-1:Chrome.2G - http://www.webpagetest.org/result/160704_6N_Y1G/

Do any of the other default values work (list below)?

.Cable
.DSL
.Dial
.3G
.3GFast
.3GSlow
.Edge
.2G
.Native
.custom

**Comment by spencershaw** [comment]
thanks andy. Seems to be ok now

On Mon, Jul 4, 2016 at 8:09 PM, Andy Davies <notifications@github.com>
wrote:

> I've just tried the following in the location field and they both work OK
>
> ec2-eu-west-1:Chrome.3G - http://www.webpagetest.org/result/160704_RZ_Y1E/
> ec2-eu-west-1:Chrome.2G - http://www.webpagetest.org/result/160704_6N_Y1G/
>
> Do any of the other default values work (list below)?
>
> .Cable
> .DSL
> .Dial
> .3G
> .3GFast
> .3GSlow
> .Edge
> .2G
> .Native
> .custom
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/andydavies/WPT-Bulk-Tester/issues/15#issuecomment-230343179>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMbZyBllw2bOpSVQV26UHK_rX8kOqsxXks5qSVprgaJpZM4JD-V3>
> .
>



-- 

*Spencer Shaw* | Chief Technical Officer

[image: Phone]:   020 7112 9321 | 07932 080811

[image: Email]:   spencer@streetlike.com

[image: website]:   www.streetlike.com

[image: Streetlike Logo]

WeHub, 2A Redbourne Avenue, Finchley, London, N3 2BS
