### ISSUE TITLE
Bulk WPT Scenario locations

### ISSUE THREAD

**Issue by spencershaw** [andydavies/WPT-Bulk-Tester#18]
Hi Andy,

Which of these locations can I use?

https://www.webpagetest.org/getLocations.php?f=html

So far, I know these work:
ec2-eu-west-1:Chrome
ec2-us-west-1:Chrome

But 
London:Chrome doesn't

**Comment by andydavies** [comment]
Assuming you've got one of the Akamai sponsored keys, then in the email it came in they'll be a list of locations.

They're normally the Dulles locations and the Akamai sponsored ones, list looks something like (some locations may have changed name by now):

Dulles_IE9
Dulles_IE10
Dulles_IE11
Dulles:Chrome
Dulles:Canary
Dulles:Firefox
Dulles:Firefox Nightly
Dulles:Safari
Dulles_Chrome40
Dulles_MotoG:Motorola G - Chrome
Dulles_MotoG:Motorola G - Chrome Beta
Dulles_MotoG:Motorola G - Chrome Dev
ec2-us-east-1:Chrome
ec2-us-east-1:IE 11
ec2-us-east-1:Firefox
ec2-us-east-1:Safari
ec2-us-west-1:Chrome
ec2-us-west-1:IE 11
ec2-us-west-1:Firefox
ec2-us-west-1:Safari
ec2-us-west-2:Chrome
ec2-us-west-2:IE 11
ec2-us-west-2:Firefox
ec2-us-west-2:Safari
ec2-eu-west-1:Chrome
ec2-eu-west-1:IE 11
ec2-eu-west-1:Firefox
ec2-eu-west-1:Safari
ec2-eu-central-1:Chrome
ec2-eu-central-1:IE 11
ec2-eu-central-1:Firefox
ec2-eu-central-1:Safari
ec2-ap-northeast-1:Chrome
ec2-ap-northeast-1:IE 11
ec2-ap-northeast-1:Firefox
ec2-ap-northeast-1:Safari
ec2-ap-southeast-1:Chrome
ec2-ap-southeast-1:IE 11
ec2-ap-southeast-1:Firefox
ec2-ap-southeast-1:Safari
ec2-ap-southeast-2:Chrome
ec2-ap-southeast-2:IE 11
ec2-ap-southeast-2:Firefox
ec2-ap-southeast-2:Safari
ec2-sa-east-1:Chrome
ec2-sa-east-1:IE 11
ec2-sa-east-1:Firefox
ec2-sa-east-1:Safari
