### ISSUE TITLE
New test instances aren't recognized

### ISSUE THREAD

**Issue by e-orlov** [andydavies/WPT-Bulk-Tester#24]
There are some new test instances, like Frankfurt_Ruxit, Falkenstein, Berlin, which haven't names like ec2-eu-central-1. On trying to add these instances like  Frankfurt_Ruxit:Chrome, after update scenarios they aren't recognized in the list of test instances.

**Comment by andydavies** [comment]
The email that had your API WebPageTest API key lists the location that an API key can be used with - primarily the Akamai supported locations, Dulles & London

There was an WebPageTest bug that allowed other locations to be used and this got fixed at some point (it's not known what fixed the bug)

So first thing to check is whether you API key actually supports the locations you're trying to use

**Comment by e-orlov** [comment]
Sure, it does. I run successful tests with locations like 

```
Frankfurt, Safari, Cable | eu-central-1:Safari
Frankfurt_EC2, Chrome, Cable | ec2-eu-central-1:Chrome
```

**Comment by josebolos** [comment]
Hi @e-orlov,

If I'm not mistaken, the list of locations at https://www.webpagetest.org/getLocations.php?f=html includes locations that are not available through the API.

This is the list of locations available through the API, the ones that you mention are not available there:
https://www.webpagetest.org/getLocations.php?f=html&k=A
