### ISSUE TITLE
Issue with long urls

### ISSUE THREAD

**Issue by dougsillars** [andydavies/WPT-Bulk-Tester#25]
With long urls (and, well, a lot of custom metrics), I hit the 2K limit for GET requests.
Here's how I made it a POST to get around that limitation:

changing lines 117-124 of the script from:
 // build API URL and submit tests
      var wptAPI = server + "/runtest.php?" + querystring;
      
      var response = UrlFetchApp.fetch(wptAPI);

TO:
      var wptAPI = server + "/runtest.php?" //+ querystring;
      var options = {
         'method' : 'post',
         'payload' : querystring
       };   
      
      var response = UrlFetchApp.fetch(wptAPI, options);

**Comment by andydavies** [comment]
@dougsillars Have you got a test case I can use for this?

**Comment by dougsillars** [comment]
I'll share a sheet with you. I was testing a *lot* of custom metrics.

**Comment by andydavies** [comment]
Thanks @dougsillars, fixed via #31

LMK if you see any issues with it
