### ISSUE TITLE
Problem adding Lighthouse metrics 

### ISSUE THREAD

**Issue by EGRFPMX** [andydavies/WPT-Bulk-Tester#26]
Hi, I want to add some lighthouse information. I activated Lighthouse, so the JSON returns the information but I am struggling to get it in to the excel.

So, for example "data.lighthouse.userAgent" gives me the user agent, and it's working.

![image](https://user-images.githubusercontent.com/64535860/80598862-e17f6d80-8a21-11ea-95c1-701bccc3b7f0.png)

But when I try to get the FCP using "data.lighthouse.audits.first-contentful-paint.numericValue", it doesn't work. 

![image](https://user-images.githubusercontent.com/64535860/80599636-222bb680-8a23-11ea-8ff8-84e2694443cc.png)

You can see the full JSON here: [https://webpagetest.org/jsonResult.php?test=200429_MG_a5034b2456c198764ee9026c7ae3a0b0&pretty=1](https://webpagetest.org/jsonResult.php?test=200429_MG_a5034b2456c198764ee9026c7ae3a0b0&pretty=1)

Anyone can help me with this?

I don't know what I am missing :(

**Comment by andydavies** [comment]
It's the hyphens in first-contentful-paint that are causing the issue but I need to track down why

`data.lighthouse.audits["first-contentful-paint"].numericValue` works as an alternative

**Comment by EGRFPMX** [comment]
> data.lighthouse.audits["first-contentful-paint"].numericValue

Working!!! Thanks!!!
