### ISSUE TITLE
Question: link to gsheet v0.5?

### ISSUE THREAD

**Issue by cweekly** [andydavies/WPT-Bulk-Tester#30]
Hi @andydavies, 
Thanks again for creating this awesome tool.

The version of the "master" spreadsheet linked from the README is labelled "v0.4":
https://docs.google.com/spreadsheets/d/1iAmQLoazddTPu08NHzp2Zk2sXzpprhIdLCpTEt3gVYU

The link in the `webpagetest.gs` comments as of the "re-sync with v0.5 spreadsheet":
https://github.com/andydavies/WPT-Bulk-Tester/blob/bf3a310b377f89345bb44921f2b452bdbef3f1c2/webpagetest.gs#L5
references "v0.1":
https://docs.google.com/spreadsheets/d/1PSmB1aa0L43ENzT_1Ry2f_oB7Z_ZESnZUZZzU85Ijys

Could you please share a link to the v0.5 spreadsheet?

Thanks! :)
Slainte,
Chris

**Comment by andydavies** [comment]
@cweekly I've done a bunch of updates a rev-d the sheet to v0.6

Link is in the readme LMK if you come across any issues

**Comment by cweekly** [comment]
@andydavies Awesome! Thanks! Digging into it today, will post issues if any. :)
