### ISSUE TITLE
Resolved: Device emulation 

### ISSUE THREAD

**Issue by cweekly** [andydavies/WPT-Bulk-Tester#32]
Hi Andy,
Thanks again for an awesome tool!

I'm using the latest sheet v0.6.
I know how to tweak the named ranges and run the "Update scenario columns" script.
Using marcel duran's npm script, I can run `webpagetest test <URL> ... --mobile --device iPhoneX` (noting the "mobile" arg is required in order for "device" to work), and -- provided the specified device string (e.g. "iPhoneX") is defined in my private instance's `mobile_devices.ini` -- it works properly. 

But with the gsheet, with "device" and "mobile" columns added to the scenarios, the tests only ever run with "Emulated Motorola G (gen 4)", ie the default mobile device. Omitting the "mobile" param, or reversing the column order, has no effect. 

I think it's a bug. Will keep an eye out for any response here and do what I can to help ensure it's reproducible.  
Slainte,
CW

**Comment by cweekly** [comment]
FTR, I've also tried configuring a "mobileDevice" parameter.

Native API:
WORKS: /runtest.php?mobileDevice=iPhoneX...

Node API wrapper:
WORKS: webpagetest test ... --mobile --device iPhoneX ...

WPT-Bulk-Tester:
FAILS: any combination | ordering of columns "device", "mobile", "mobileDevice"

**Comment by andydavies** [comment]
Thanks @cweekly I'll take a look and see if I can work out what's happening

**Comment by cweekly** [comment]
Hey @andydavies your timing is amazing; I just figured it out. Thanks though! :)
