### ISSUE TITLE
Question: How to use scripting

### ISSUE THREAD

**Issue by fwebdev** [andydavies/WPT-Bulk-Tester#9]
Hi, 

I would like to use a script for a page login.
How do I choose for which scenario or testrun he should call that script?

Thanks you
Florian

**Comment by andydavies** [comment]
Scripting certainly works via the WPT API but the tests from the spreadsheet that include a script seem to fail at the moment, so I'm having a look into it.

**Comment by andydavies** [comment]
OK here's an example of a sheet with tests that use a script - https://docs.google.com/spreadsheets/d/1VU7QJTOexSlOSLS4KGThOJA8eP1kSN7--rpAwMaEudo/edit?usp=sharing

You'll need to add a script column using the ParametersMap in the Settings Tab, then after you've run the menu item to update the Scenarios column headings paste the script into a single cell

I'd recommend testing the script in WPT first to make sure it works

**Comment by fwebdev** [comment]
Nice! Thank you very much!
